### ISSUE TITLE
Something strange happens to arrays in variables

### ISSUE THREAD

**Issue by tmjoen** [labtwentyfive/apollo-absinthe-upload-client#1]
Hi, and first of all thanks for the client!

I have a strange problem with it though.

When I try to upload to absinthe through this mutation:

```
mutation CreatePost($post_params: CreatePostParams) {
  create_post(
    post_params: $post_params,
  ) {
    id
  }
}
```

where `$post_params` =

```
post_params = {
  header: 'Test header',
  cover: <file>,
  illustrators: [5, 7],
  clients: [1, 2, 3]
}
```

something happens either while traversing the object looking for files, or when the mutation is sent by `fetch`.

When I remove the `cover` file from the params, and the upload client bypasses this and runs `return super.fetchFromRemoteEndpoint({ request, options });` instead, my `illustrators` and `clients` arrays are parsed correctly as [lists] by the absinthe backend.

When `cover` is there and the upload client runs its logic, absinthe tries to read the `illustrators` and `clients` arrays as objects instead (they are parsed as %{} maps, instead of lists).

I have tried digging around but I'm afraid I didn't find out much more.

Do you have any idea what this could be, and how to solve it?

Thanks for your time!

Best,

T

**Comment by clentfort** [comment]
Fixed in #2. Thanks again for the Pull Request.
