### ISSUE TITLE
Apollo Client v2 Support

### ISSUE THREAD

**Issue by rhysldavis** [labtwentyfive/apollo-absinthe-upload-client#5]
Hey Guys,

Thanks for making this package.

Apollo changed their setup structure to utilise HttpLink rather than networkInterface.  Is there a plan to support v2?

**Comment by clentfort** [comment]
Unfortunately, there are no current plans to support HttpLink.

**Comment by ihorkatkov** [comment]
Rewritten version for v2 here https://www.npmjs.com/package/apollo-absinthe-upload-link based on this package. @clentfort  thanks
Feedback or collaboration really appreciated

**Comment by clentfort** [comment]
Thanks so much. :)
